"""
plot_vars.py -- lookup functions for plotting variables.

Follows the pltutil.py pattern: many small, single-purpose functions,
each keyed by a short variable name, each with its own dict and a
sensible default via .get(). Add a variable by adding one line to
whichever function(s) it actually needs -- you never have to fill in
every property for every variable.

Data below was mechanically derived from a verified extraction of every
plot(...) call in SummaryPlots.py (55 unique configs, cross-checked by
regex against the source -- see git history / prior plot_vars.py for the
extraction notes). Known item-number collisions from that extraction are
preserved as separate variable names below (e.g. mt_vhlep vs mt_tthlep).
"""

def get_expr(varname):
    """RDataFrame branch/expression for a variable."""
    exprs = {
        'dimu_mass': 'HiggsCandCorrMass',
        'mva': 'discrMVA0',
        'category_vlcat': 'category',
        'category_ttlcat': 'category',
        'category_tthcat': 'category',
        'muon1_pt': 'Muon1_pt',
        'muon2_pt': 'Muon2_pt',
        'muon1_eta': 'Muon1_eta',
        'muon2_eta': 'Muon2_eta',
        'dimuon_pt': 'HiggsCandCorrPt',
        'dimuon_eta': 'HiggsCandCorrEta',
        'muon1_norm_pt': 'Muon1_norm_pt',
        'muon2_norm_pt': 'Muon2_norm_pt',
        'dimuon_rapidity': 'HiggsCandCorrRapidity',
        'costhetacs': 'cosThetaCS',
        'phistarcs': 'phiStarCS',
        'muon1_sip3d': 'Muon1_sip3d',
        'muon2_sip3d': 'Muon2_sip3d',
        'fsrph_pt': 'FsrPH_pt',
        'muon1_phi': 'Muon1_phi',
        'muon2_phi': 'Muon2_phi',
        'deta_muons': 'fabs(Muon1_eta-Muon2_eta)',
        'mjj': 'Mjj',
        'detajj': 'dEtaJJ',
        'rpt': 'RPt',
        'zepvar': 'ZepVar',
        'jetvbf1_pt': 'jetVBF1_Pt',
        'jetvbf2_pt': 'jetVBF2_Pt',
        'jetvbf1_eta': 'jetVBF1_Eta',
        'jetvbf2_eta': 'jetVBF2_Eta',
        'puppimet_pt_vbf': 'PuppiMET_pt',
        'lepton_pt': 'Lepton_Pt',
        'puppimet_pt_vhlep': 'PuppiMET_pt',
        'mt_vhlep': 'mt',
        'lepton_eta': 'Lepton_Eta',
        'lepton2_pt': 'Lepton2_Pt',
        'puppimet_pt_tthlep_tthad': 'PuppiMET_pt',
        'mt_tthlep': 'mt',
        'ht': 'HT',
        'jet1_pt_tthlep': 'Jet1_Pt',
        'jet1_eta': 'Jet1_Eta',
        'goodwjj_mass': 'goodWjj_mass',
        'goodwjj_discr': 'goodWjj_discr',
        'goodwjj_pt': 'goodWjj_pt',
        'goodwjj_eta': 'goodWjj_eta',
        'goodwjjptoverhpt': 'goodWjj_pt/HiggsCandCorrPt',
        'detawjjh': 'dEtaWjjH',
        'dphiwjjh': 'dPhiWjjH',
        'jet1_pt_tthad': 'Jet1_Pt',
        'wtopjetmass': 'WTopJetMass',
        'wtopjetdiscr': 'WTopJetDiscr',
        'njets': 'nGoodJetsAll',
        'nbmjets': 'nBMjets',
        'topmassreco': 'TopMassReco',
        'deta_j1j2': 'dEta_j1j2',
        'mindr_h_bjet': 'mindR_H_BJet',
        'mindr_h_anyjet': 'mindR_H_AnyJet',
        'dphimeth': 'dPhiMETH',
        'puppimet_ptoverhpt': 'PuppiMET_pt/HiggsCandCorrPt',
        'puppimet_pt_zinv': 'PuppiMET_pt',
        'deltaphimetmu1': 'deltaPhi(PuppiMET_phi,Muon1_phi)',
        'deltaphimetmu2': 'deltaPhi(PuppiMET_phi,Muon2_phi)',
    }
    return exprs.get(varname, varname)  # fallback: assume the name is the branch


def get_binning(varname):
    """Return (nbin, low, high) for a variable, or None if unknown."""
    binning = {
        'dimu_mass': (130, 70.0, 200.0),
        'mva': (100, 0.0, 1.0),
        'category_vlcat': (5, 0.0, 5.0),
        'category_ttlcat': (6, 0.0, 6.0),
        'category_tthcat': (4, 0.0, 4.0),
        'muon1_pt': (100, 0.0, 200.0),
        'muon2_pt': (100, 0.0, 200.0),
        'muon1_eta': (60, -3.0, 3.0),
        'muon2_eta': (60, -3.0, 3.0),
        'dimuon_pt': (100, 0.0, 400.0),
        'dimuon_eta': (60, -3.0, 3.0),
        'muon1_norm_pt': (100, 0.0, 2.0),
        'muon2_norm_pt': (100, 0.0, 2.0),
        'dimuon_rapidity': (60, -3.0, 3.0),
        'costhetacs': (50, -1.0, 1.0),
        'phistarcs': (50, -3.14159, 3.14159),
        'muon1_sip3d': (100, 0.0, 20.0),
        'muon2_sip3d': (100, 0.0, 20.0),
        'fsrph_pt': (200, 0.1, 20.1),
        'muon1_phi': (60, -3.14, 3.14),
        'muon2_phi': (60, -3.14, 3.14),
        'deta_muons': (60, 0.0, 6.0),
        'mjj': (100, 0.0, 1000.0),
        'detajj': (100, 0.0, 10.0),
        'rpt': (100, 0.0, 1.0),
        'zepvar': (100, 0.0, 2.0),
        'jetvbf1_pt': (200, 0.0, 200.0),
        'jetvbf2_pt': (200, 0.0, 200.0),
        'jetvbf1_eta': (100, -5.0, 5.0),
        'jetvbf2_eta': (100, -5.0, 5.0),
        'puppimet_pt_vbf': (100, 0.0, 500.0),
        'lepton_pt': (100, 10.0, 100.0),
        'puppimet_pt_vhlep': (300, 0.0, 300.0),
        'mt_vhlep': (150, 0.0, 150.0),
        'lepton_eta': (60, -3.0, 3.0),
        'lepton2_pt': (100, 10.0, 100.0),
        'puppimet_pt_tthlep_tthad': (100, 0.0, 500.0),
        'mt_tthlep': (30, 0.0, 150.0),
        'ht': (200, 0.0, 1000.0),
        'jet1_pt_tthlep': (150, 10.0, 160.0),
        'jet1_eta': (100, -5.0, 5.0),
        'goodwjj_mass': (50, 60.0, 110.0),
        'goodwjj_discr': (50, 0.75, 1.0),
        'goodwjj_pt': (40, 150.0, 550.0),
        'goodwjj_eta': (60, -3.0, 3.0),
        'goodwjjptoverhpt': (50, 0.0, 5.0),
        'detawjjh': (60, 0.0, 2.5),
        'dphiwjjh': (100, 0.0, 6.28),
        'jet1_pt_tthad': (100, 10.0, 200.0),
        'wtopjetmass': (150, 50.0, 200.0),
        'wtopjetdiscr': (50, 0.5, 1.0),
        'njets': (10, 0.0, 10.0),
        'nbmjets': (10, 0.0, 10.0),
        'topmassreco': (35, 0.0, 350.0),
        'deta_j1j2': (30, 0.0, 3.0),
        'mindr_h_bjet': (30, 0.0, 6.5),
        'mindr_h_anyjet': (30, 0.0, 6.5),
        'dphimeth': (50, 0.0, 3.5),
        'puppimet_ptoverhpt': (50, 0.0, 5.0),
        'puppimet_pt_zinv': (400, 0.0, 400.0),
        'deltaphimetmu1': (50, 0.0, 3.5),
        'deltaphimetmu2': (50, 0.0, 3.5),
    }
    return binning.get(varname)


def get_xlabel(varname):
    """x-axis title for a variable."""
    labels = {
        'dimu_mass': 'm_{#mu#mu} [GeV]',
        'mva': 'MVA discr',
        'category_vlcat': 'category',
        'category_ttlcat': 'category',
        'category_tthcat': 'category',
        'muon1_pt': 'p_{T}^{#mu_{1}} [GeV]',
        'muon2_pt': 'p_{T}^{#mu_{2}} [GeV]',
        'muon1_eta': '#eta^{#mu_{1}}',
        'muon2_eta': '#eta^{#mu_{2}}',
        'dimuon_pt': 'p_{T}^{#mu#mu} [GeV]',
        'dimuon_eta': '#eta_{#mu#mu}',
        'muon1_norm_pt': 'p_{T}^{#mu_{1}}/m_{#mu#mu}',
        'muon2_norm_pt': 'p_{T}^{#mu_{2}}/m_{#mu#mu}',
        'dimuon_rapidity': 'y_{#mu#mu}',
        'costhetacs': 'cos#theta_{CS}',
        'phistarcs': '#phi^{*}_{CS}',
        'muon1_sip3d': 'Muon1_sip3d',
        'muon2_sip3d': 'Muon2_sip3d',
        'fsrph_pt': 'p^{T}_{#gammaFSR} [GeV]',
        'muon1_phi': '#phi_{#mu^{1}}',
        'muon2_phi': '#phi_{#mu^{2}}',
        'deta_muons': '|#Delta#eta(#mu^{1}, #mu^{2})|',
        'mjj': 'Mjj',
        'detajj': 'dEtaJJ',
        'rpt': 'Rpt',
        'zepvar': 'ZepVar',
        'jetvbf1_pt': 'jetVBF1_Pt',
        'jetvbf2_pt': 'jetVBF2_Pt',
        'jetvbf1_eta': '#eta jetVBF1',
        'jetvbf2_eta': '#eta jetVBF2',
        'puppimet_pt_vbf': 'PuppiMET_Pt',
        'lepton_pt': 'Lepton_Pt',
        'puppimet_pt_vhlep': 'PuppiMET_Pt',
        'mt_vhlep': 'mt',
        'lepton_eta': 'Lepton_Eta',
        'lepton2_pt': 'Lepton2_Pt',
        'puppimet_pt_tthlep_tthad': 'PuppiMET_Pt',
        'mt_tthlep': 'mt',
        'ht': 'HT',
        'jet1_pt_tthlep': 'Jet1_Pt',
        'jet1_eta': 'Jet1_Eta',
        'goodwjj_mass': 'goodWjj_mass',
        'goodwjj_discr': 'goodWjj_discr',
        'goodwjj_pt': 'goodWjj_pt',
        'goodwjj_eta': 'goodWjj_eta',
        'goodwjjptoverhpt': 'goodWjjPtOverHpt',
        'detawjjh': 'dEtaWjjH',
        'dphiwjjh': 'dPhiWjjH',
        'jet1_pt_tthad': 'Jet1_Pt',
        'wtopjetmass': 'WTopJetMass',
        'wtopjetdiscr': 'WTopJetDiscr',
        'njets': 'Njets',
        'nbmjets': 'nBMjets',
        'topmassreco': 'TopMassReco',
        'deta_j1j2': 'dEta_j1j2',
        'mindr_h_bjet': 'mindR_H_BJet',
        'mindr_h_anyjet': 'mindR_H_AnyJet',
        'dphimeth': 'dPhiMETH',
        'puppimet_ptoverhpt': 'PuppiMET_PtOverHpt',
        'puppimet_pt_zinv': 'PuppiMET_Pt',
        'deltaphimetmu1': 'deltaPhiMETMu1',
        'deltaphimetmu2': 'deltaPhiMETMu2',
    }
    return labels.get(varname, varname)


def get_logy_vars():
    """Variables plotted with a log y-axis. Opt-in list; anything not here
    is drawn linear."""
    return [
        'dimu_mass',
        'mva',
        'muon1_pt',
        'muon2_pt',
        'muon1_eta',
        'muon2_eta',
        'dimuon_pt',
        'muon1_sip3d',
        'muon2_sip3d',
        'deta_muons',
        'mjj',
        'detajj',
        'rpt',
        'zepvar',
        'jetvbf1_pt',
        'jetvbf2_pt',
        'jetvbf1_eta',
        'jetvbf2_eta',
        'puppimet_pt_vhlep',
        'puppimet_pt_tthlep_tthad',
        'ht',
        'goodwjj_mass',
        'goodwjj_discr',
        'goodwjj_pt',
        'goodwjj_eta',
        'goodwjjptoverhpt',
        'detawjjh',
        'dphiwjjh',
        'wtopjetmass',
        'njets',
        'topmassreco',
        'deta_j1j2',
        'mindr_h_bjet',
        'mindr_h_anyjet',
        'dphimeth',
        'puppimet_ptoverhpt',
        'deltaphimetmu1',
        'deltaphimetmu2',
    ]


def get_bin_labels(varname):
    """Custom x-axis bin labels for categorical (category-index) variables."""
    bin_labels = {
        "category_vlcat": ["", "H_{#mu#mu}+e", "H_{#mu#mu}+ee", "H_{#mu#mu}+#mu",
                            "H_{#mu#mu}+#mu#mu", "H_{#mu#mu}+e#mu"],
        "category_ttlcat": ["", "H_{#mu#mu}+e", "H_{#mu#mu}+ee", "H_{#mu#mu}+#mu",
                             "H_{#mu#mu}+#mu#mu", "H_{#mu#mu}+e#mu"],
        "category_tthcat": ["", "n_top", "n_W", "resolved (5jets)"],
    }
    return bin_labels.get(varname)


def get_ratio_range(varname):
    """(low, high) for the ratio-pad y-axis. Falls back to a wide default."""
    ranges = {
        "dimu_mass": (0.90, 1.10),
    }
    return ranges.get(varname, (0.5, 1.5))


def get_blind_range(varname):
    """(low, high) mass window blinded in data, if this variable is blinded."""
    blinds = {
        "dimu_mass": (110, 150),
    }
    return blinds.get(varname)


def get_source_info(varname):
    """Traceability only: which SummaryPlots.py function this came from, whether
    it is currently active or only inside a commented-out block, and the
    original numeric `item` code it replaces."""
    info = {
        'dimu_mass': {"source": 'draw_mass', "active": True, "item": 4},
        'mva': {"source": 'draw_mva / plotVBF / plotVHlep / plotTTHlep / plotVHhad / plotTThad / plotZinvH', "active": True, "item": 99},
        'category_vlcat': {"source": 'draw_category(VLcat) / plotVHlep', "active": True, "item": 210},
        'category_ttlcat': {"source": 'draw_category(TTLcat) / plotTTHlep', "active": True, "item": 210},
        'category_tthcat': {"source": 'draw_category(TTHcat) / plotTThad', "active": True, "item": 211},
        'muon1_pt': {"source": 'plotMuons', "active": True, "item": 10},
        'muon2_pt': {"source": 'plotMuons', "active": True, "item": 11},
        'muon1_eta': {"source": 'plotMuons', "active": True, "item": 12},
        'muon2_eta': {"source": 'plotMuons', "active": True, "item": 13},
        'dimuon_pt': {"source": 'plotMuons', "active": True, "item": None},
        'dimuon_eta': {"source": 'plotMuons', "active": True, "item": None},
        'muon1_norm_pt': {"source": 'plotMuons', "active": True, "item": None},
        'muon2_norm_pt': {"source": 'plotMuons', "active": True, "item": None},
        'dimuon_rapidity': {"source": 'plotMuons', "active": True, "item": None},
        'costhetacs': {"source": 'plotMuons', "active": True, "item": None},
        'phistarcs': {"source": 'plotMuons', "active": True, "item": None},
        'muon1_sip3d': {"source": 'plotMuons (VLcat/TTLcat/TTHcat only)', "active": True, "item": 14},
        'muon2_sip3d': {"source": 'plotMuons (VLcat/TTLcat/TTHcat only)', "active": True, "item": 15},
        'fsrph_pt': {"source": 'plotMuons', "active": False, "item": 16},
        'muon1_phi': {"source": 'plotMuons', "active": False, "item": 18},
        'muon2_phi': {"source": 'plotMuons', "active": False, "item": 19},
        'deta_muons': {"source": 'plotMuons', "active": True, "item": 20},
        'mjj': {"source": 'plotVBF', "active": False, "item": 100},
        'detajj': {"source": 'plotVBF', "active": False, "item": 101},
        'rpt': {"source": 'plotVBF / plotVHlep / plotVHhad / plotZinvH', "active": False, "item": 102},
        'zepvar': {"source": 'plotVBF', "active": False, "item": 103},
        'jetvbf1_pt': {"source": 'plotVBF', "active": False, "item": 104},
        'jetvbf2_pt': {"source": 'plotVBF', "active": False, "item": 105},
        'jetvbf1_eta': {"source": 'plotVBF', "active": False, "item": 106},
        'jetvbf2_eta': {"source": 'plotVBF', "active": False, "item": 107},
        'puppimet_pt_vbf': {"source": 'plotVBF', "active": False, "item": 301},
        'lepton_pt': {"source": 'plotVHlep / plotTTHlep', "active": False, "item": 201},
        'puppimet_pt_vhlep': {"source": 'plotVHlep', "active": False, "item": 301},
        'mt_vhlep': {"source": 'plotVHlep', "active": False, "item": 212},
        'lepton_eta': {"source": 'plotTTHlep', "active": False, "item": 203},
        'lepton2_pt': {"source": 'plotTTHlep', "active": False, "item": 202},
        'puppimet_pt_tthlep_tthad': {"source": 'plotTTHlep / plotTThad', "active": False, "item": 301},
        'mt_tthlep': {"source": 'plotTTHlep', "active": False, "item": 212},
        'ht': {"source": 'plotTTHlep / plotTThad', "active": False, "item": 263},
        'jet1_pt_tthlep': {"source": 'plotTTHlep', "active": False, "item": 260},
        'jet1_eta': {"source": 'plotTTHlep / plotTThad', "active": False, "item": 265},
        'goodwjj_mass': {"source": 'plotVHhad', "active": False, "item": 251},
        'goodwjj_discr': {"source": 'plotVHhad', "active": False, "item": 252},
        'goodwjj_pt': {"source": 'plotVHhad', "active": False, "item": 253},
        'goodwjj_eta': {"source": 'plotVHhad', "active": False, "item": 255},
        'goodwjjptoverhpt': {"source": 'plotVHhad', "active": False, "item": 254},
        'detawjjh': {"source": 'plotVHhad', "active": False, "item": 255},
        'dphiwjjh': {"source": 'plotVHhad', "active": False, "item": 256},
        'jet1_pt_tthad': {"source": 'plotTThad', "active": False, "item": 260},
        'wtopjetmass': {"source": 'plotTThad', "active": False, "item": 261},
        'wtopjetdiscr': {"source": 'plotTThad', "active": False, "item": 262},
        'njets': {"source": 'plotMuons (ggHcat/TTHcat only)', "active": True, "item": 264},
        'nbmjets': {"source": 'plotTThad', "active": False, "item": 267},
        'topmassreco': {"source": 'plotTThad', "active": False, "item": 266},
        'deta_j1j2': {"source": 'plotTThad', "active": False, "item": 268},
        'mindr_h_bjet': {"source": 'plotTThad', "active": False, "item": 269},
        'mindr_h_anyjet': {"source": 'plotTThad', "active": False, "item": 270},
        'dphimeth': {"source": 'plotZinvH', "active": False, "item": 305},
        'puppimet_ptoverhpt': {"source": 'plotZinvH', "active": False, "item": 302},
        'puppimet_pt_zinv': {"source": 'plotZinvH', "active": False, "item": 301},
        'deltaphimetmu1': {"source": 'plotZinvH', "active": False, "item": 303},
        'deltaphimetmu2': {"source": 'plotZinvH', "active": False, "item": 304},
    }
    return info.get(varname)
